### ISSUE TITLE
Dead link in "RFP Size" section

### ISSUE THREAD

**Issue by s3lph** [dect-e/howto-dect#4]
https://github.com/dect-e/howto-dect/blob/b380725391d0a50ca3f735e600ea13e522b4239d/index.md?plain=1#L423
This link is dead (404), and I couldn't find the same document elsewhere through a quick search.

**Comment by n-st** [comment]
Thanks for the hint!
Since we were only referencing the brochure for the gen 3 / gen 4 comparison photo, I've replaced it (96f7547) with a photo taken by Eventphone that shows both hardware generations.
